### ISSUE TITLE
Is it possible to support custom fields without having to re-implement Fable.Form.Simple and Fable.Form.Simple.Feliz.Bulma?

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fable.Form#12]

**Comment by zelenij** [comment]
Hi, this sounds like a good question. Any update on it? Or in general, a simple example of a custom form field?

**Comment by MangelMaxime** [comment]
Hello @zelenij,

sorry I missed your comment.

I didn't make progress on this question yet. About an example, all the fields implemented in Fable.Form.Simple are actually custom form field build on top of the generic API provided by Fable.Form.

So if you are interested in creating your own field you can focus on one of them and see how it is handled.

In the future, I should write a blog post / step by step example on how to build a form abstraction from scratch.

**Comment by MangelMaxime** [comment]
Investigate the idea of adding a new case `Extensions` to the `Field` allowing people to register custom fields without.

**Comment by MangelMaxime** [comment]
Version 5 allows to create or customise field without forking the library.
