### ISSUE TITLE
Assistance: Simple Form implementation

### ISSUE THREAD

**Issue by TerenceHinrichsen** [MangelMaxime/Fable.Form#23]
I am trying to publish a `Material-UI` implementation for Fable.Form.Simple. The project compiles and everything looks good, but when I add a reference to it from another project (via Nuget) I get:
```
client: C:/Users/Terence/Projects/Safe-Playground/src/Client/Index.fs(202,29): (210,47) error FSHARP: The type referenced 
through 'Fable.Form.Simple.Form.View.ViewConfig`2' is defined in an assembly that is not referenced. You must add a reference 
to assembly 'Fable.Form.Simple'. (code 74)
```
I have added the reference to Fable.Form.Simple in my `paket.dependencies`, even added an `open` to the top of both my fsi and fs file (compiler is complaining that it is not necessary), but I am not able to add the reference to the implementation.

I feel like a complete idiot for not seeing where I am missing the reference and what I am doing wrong, any advise - (even if you just tell me where to look please) would be highly appreciated!

[Source](https://github.com/TerenceHinrichsen/Fable.Form.Simple.MaterialUI)
[Nuget](https://www.nuget.org/packages/Fable.Form.Simple.MaterialUI/0.0.5)

**Comment by MangelMaxime** [comment]
Hello @TerenceHinrichsen,

in your library fsproj your forgot to add the special `fable` folder with the source code in it. This is needed when you release a library and not just pure binding (no code).

[Fable Docs - Author a Fable library](https://fable.io/docs/your-fable-project/author-a-fable-library.html)

If you used the `.fsproj` from this repository as an exemple, I am actually doing it in a special way by using the [Directory.Build.props](https://github.com/MangelMaxime/Fable.Form/blob/main/Directory.Build.props) file to add it only once.

This is real cool to see someone writing its own view layer on top of Fable.Form, I hope it was not too cryptic/hard :)

**Comment by TerenceHinrichsen** [comment]
As simple as that. THANK you again for your help. New version now working when referenced, just a few little issues to iron out!
