### ISSUE TITLE
There seem to be no way to flag a text field as optional (not required)

### ISSUE THREAD

**Issue by zelenij** [MangelMaxime/Fable.Form#28]
Subject...

**Comment by MangelMaxime** [comment]
I forgot to expose the function for it, it is now available.

See the doc comment, to know more about how to use it:

https://github.com/MangelMaxime/Fable.Form/blob/4cb633cc1b5177632448f19cae70483dbdc8d914/packages/Fable.Form.Simple/Form.fsi#L186-L217
