### ISSUE TITLE
Readonly feature 

### ISSUE THREAD

**Issue by LuisFX** [MangelMaxime/Fable.Form#33]
It would be nice to have the ability to render the form as  readonly.

Such as if we have a property:

RenderMode = Review | Edit

...where if form is in "ReadOnly" mode, it would display "labels" instead of the regular "input" fields? (which would essentially be the same input fields with the "readonly" modifier, and a class to take away the border from the input field).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/1130772/177856719-043da1d7-0373-4c4b-9932-17109ca5d6ef.png">

The purpose would be to be able to review the same data in the same layout that it was input but non-editable. 

The form would be able to  switch form edit <-> review on demand.

**Comment by LuisFX** [comment]
I see there's a "disabled" flag throughout the fields in the source code, I just don't know how to put the entire form in "disabled" mode.

**Comment by MangelMaxime** [comment]
Hello,

Issue #32 is related to your problem.

I forget to expose the `disable` function from `Fable.Form.Simple` like it is done for `append` or `andThen` for example.

https://github.com/MangelMaxime/Fable.Form/blob/27b3fccf5f8adb3ce8bf879785e00e493abd548d/packages/Fable.Form.Simple/Form.fs#L57-L75

If this is urgent, it is possible to copy/paste the code from #32 as a temporary solution.

Once, the function is exposed, you can do things like:

*Disable all the field from the form*

```fs
    Form.succeed onSubmit
        |> Form.append emailField
        |> Form.append passwordField
        |> Form.append rememberMe
        |> Form.disable
```

*Disable only the email and password but **not** remember field from the form*

```fs
    Form.succeed onSubmit
        |> Form.append emailField
        |> Form.append passwordField
        |> Form.disable
        |> Form.append rememberMe
```

If needed you can disable a single field when defining it:

```fs
    let passwordField =
        Form.passwordField
            {
                Parser = Ok
                Value =
                    fun values -> values.Password
                Update =
                    fun newValue values ->
                        { values with Password = newValue }
                Error =
                    fun _ -> None
                Attributes =
                    {
                        Label = "Password"
                        Placeholder = "Your password"
                        HtmlAttributes = [ ]
                    }
            }
        |> Form.Simple.disable
```

**Comment by LuisFX** [comment]
Thank you, @MangelMaxime ! This exactly what I was looking for!
