### ISSUE TITLE
Should I remove the fsi files?

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fable.Form#36]
When writing Fable.Form I discovered the .fsi file feature of F#

I liked the fact that it made everything private by default, however I am wondering if this not confusing potential readers/contributors

It also makes the code navigation less friendly

Should I remove them?

**Comment by LuisFX** [comment]
I have a mixed feeling about .fsi files. To be honest, Fable.Form is the first project I ever saw them in, so it was very confusing at first. 

It took only one read at the official documentation to understand their place, and now I think they can be useful. That said... I think they add unnecessary complexity and adoption is low (F# adoption in general is low, fsi is even lower), so it's confusing to new readers.

**Comment by LuisFX** [comment]
Got it, I think I now understand the goal of fsi files... which makes me very nervous also, because one of our projects is growing in complexity (and codebase) and Ionide seems to take a dive often. I now fear the solution (eventually) will be littering our project with fsi files 😭

**Comment by MangelMaxime** [comment]
They are removed in #54
